### ISSUE TITLE
where can I find this?

### ISSUE THREAD

**Issue by liamxg** [nrennie/misc#2]
<img width="799" alt="image" src="https://user-images.githubusercontent.com/46078579/205208401-836049dc-f447-4590-85fd-f8fd1d8554df.png">

**Comment by nrennie** [comment]
`list.files()` is a function. When you run it, it will return a list of files that are in the directory you specify as the first argument. I can't upload it as it's not a dataset.

**Comment by nrennie** [comment]
No, I'm not going to upload my personal files. I'm happy to share code, but not all of my personal files. The idea of sharing this code is that you adapt it for your own needs, not scan through my personal files.
