### ISSUE TITLE
failed

### ISSUE THREAD

**Issue by liamxg** [nrennie/misc#3]
<img width="908" alt="image" src="https://user-images.githubusercontent.com/46078579/205213475-9f6b6a48-0524-4702-b6c0-a2c0252faf9e.png">

**Comment by nrennie** [comment]
Why are you raising an issue here? Please read the documentation for `getbb()`. The connection has timed out.

Again, if you are raising an issue, please:
- link to the file (I have no idea which file is from).
- include code, not screenshots of code.

You are currently raising a number of issues on projects that are maintained in my personal time. Please don't continue to create issues of screenshots of code errors with no comment or description.
